name = "OrdinalScores"
uuid = "2658d65b-60a5-416c-ab6c-22ae91cae222"
authors = ["Michael <michael.groom@sydney.edu.au>"]
version = "0.1.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CategoricalDistributions = "af321ab8-2d2e-40a6-b165-3d674595d28e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ScientificTypesBase = "30f210dd-8aff-4c5f-94ba-8e64358c1161"
StatisticalMeasuresBase = "c062fc1d-0d66-479b-b6ac-8b44719de4cc"

[compat]
Aqua = "0.8"
CategoricalArrays = "0.10, 1"
CategoricalDistributions = "0.1, 0.2"
Distributions = "0.25"
ScientificTypesBase = "3.0.0"
StatisticalMeasures = "0.1.6"
StatisticalMeasuresBase = "0.1"
Test = "1.9, 1.10, 1.11"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StatisticalMeasures = "a19d573c-0a75-4610-95b3-7071388c7541"

[targets]
test = ["Aqua", "Test", "StatisticalMeasures"]
